server:
  port: 18083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        ip: localhost
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    #mysql读取数据库数据时间是会再之前的基础上-8返回
    url: jdbc:mysql://localhost:3306/guli_wms?serverTimezone=GMT%2B8
    username: root
    password: qwertyuiop
  redis:
    host: localhost
    port: 6379
feign:
  sentinel:
    enable: true
#    数据库
mybatis-plus:
  mapper-locations: classpath:mapper/wms/**/*.xml
  global-config:
    id-type: auto
  type-aliases-package: com.atguigu.gmall.wms.entity
logging:
  level:
    com.atguigu.gmall: debug